### ISSUE TITLE
LoadError

### ISSUE THREAD

**Issue by bwvoss** [JoshCheek/what-we-ve-got-here-is-an-error-to-communicate#6]

**Comment by JoshCheek** [comment]
```ruby
require 'omg'

# ~> LoadError
# ~> cannot load such file -- omg
```

Can probably identify what file they meant to require:

* If its in their current project, then they probably got the require path wrong (common one I see among noobs is `require "./whatever"` and then they run that from different directories)
* Or the `$LOAD_PATH` is wrong
* If its a gem (could just keep a big list of gem names to gem paths) then they probably need to `gem install` it
* Otherwise, maybe its a file that they haven't made yet, in which case, we can't really know that
* Or could be a file that they renamed, but that's a lot harder to check for (ie either track files we've seen or read their git/svn/whatever history, which sounds difficult and fragile)

Assuming you can identify why that error occurred, its pretty straightforward to suggest the fix.

**Comment by JoshCheek** [comment]
I think for iteration 2, I'd like to see context before and after. Lets assume 5 lines for now, eventually eventually the expression that contains the require statement (presumably that just means 1 line near the top of the file, but if its inside a method or a loop, then that could be relevant).

Lets also check to see if the file is in any of the directories in the `$LOAD_PATH`, and if so, report that to the user. If they're using RSpec, this will naturally allow us to check `lib`. We can deal with more nuanced searching, and guessing about misspellings in later iterations.

**Comment by JoshCheek** [comment]
Synopsis for Iteration 2 (#31)
---------------------------------------

I'm going to mark this one closed for now for. 

A lot of good work got done, such as the creation of a [Project](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/blob/bb351fed5d1d24f810e41fee64c984cac7a19ada/lib/error_to_communicate/project.rb) class. I expect it to continually grow more empowered/correct as we wind up needing to ask it questions like whether there are candidate files we should look at.

Completed
---------------

It correctly identifies and marks the relevant lines from the backtrace, omitting the lines from within Rubygems (RG [redefines require](https://github.com/rubygems/rubygems/blob/eb95198f589d139afe39ebaa4c28268472121e61/lib/rubygems/core_ext/kernel_require.rb#L38)). It finds as many as two interesting locations: **the require statement** (assumed to be the first line that is not within rubygems), and **the statement in the lib dir** that led to the require statement (ie you may require give a path to a gem, which ultimately performs the require, so you're potentially interested in both of these locations).

Descoped
--------------

I descoped finding files in the `$LOAD_PATH`, because my analysis of how this should work (see "Future Work" section below), implies it deserves a little bit more thought about how it should work, where the responsibility belongs, etc. That should just be its own story, I think.

Most Relevant Commits
--------------------------------

https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/compare/06836060a8c93add36bf5b189e42118d7b1ae66a...bb351fed5d1d24f810e41fee64c984cac7a19ada

Future Work
-----------------

I thought through what else we ought to do for this, they're documented in comments at the bottom of the [load_error_spec](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/blob/bb351fed5d1d24f810e41fee64c984cac7a19ada/spec/heuristic/load_error_spec.rb#L169-194). Future 

I also looked through MRI source, and found that there is at least one other interesting `LoadError` in there, which is different from this one, I gave it [its own story](https://github.com/JoshCheek/what-we-ve-got-here-is-an-error-to-communicate/issues/40)
